# mamba env create --file environment.yml
# mamba env update --file environment.yml
# conda activate cool_planet
name: cool_planet
channels:
  - conda-forge
dependencies:
  - pdr # [P]lanetary [D]ata [R]eader - A single function to read all Planetary Data System (PDS) data into Python
  - pandas
  - pdpipe
  
  - xarray
  # For accelerating xarray
  - scipy
  - bottleneck
  - numbagg
  - flox # fast & furious GroupBy reductions for xarray and dask
  
  - astropy

  - jupyter
  - fastai::nbdev
  - fastai::fastcore

  - bokeh<3 # pytplot compatibility
  - seaborn
  - altair
  - loguru
  - tqdm
  - grpcio # used in `modin`, using conda for (Apple Silicon) Support
  - pip
  - pip:
    - modin[ray]
    - swifter # efficiently applies any function to a pandas dataframe or series in the fastest available manner
    - speasy # Python client for Space Physics web services such as CDAWEB or AMDA.
    - pycdfpp # fast CDF reader
    - multipledispatch
    - vegafusion[embed]
    - polars
    - pyspedas @ git+https://github.com/spedas/pyspedas
    - xarray-einstats