# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/planet',
                'doc_host': 'https://Beforerr.github.io',
                'git_url': 'https://github.com/Beforerr/planet',
                'lib_path': 'planet'},
  'syms': {'planet.core': {'planet.core.foo': ('core.html#foo', 'planet/core.py')}}}
